
include "/stdlib/jdk/21/amazon.conf"

app {
    display-name = "Papertrack"
    fsname = "papertrack"
    windows.exe-name = "Papertrack"
    vendor = "Your Company"
    version = "1.0.0"
    machines = [ windows.x86-64 ]
    site.base-url = "https://github.com/realtechsolutions/Papertrack_compose.git"
    vcs-url = "https://github.com/realtechsolutions/Papertrack_compose.git"
    # Icon (PNG, will be converted for all platforms)
    icons = "logo.png"
    inputs = "composeApp/build/libs/composeApp-jvm.jar"
    jvm.gui.main-class = "in.realtechsolns.papertrack.MainKt"
    # Linux packages (if you're building those too)
   # linux.deb.enabled = true

    # Windows MSIX config
    windows {
        # Important: Sign the MSIX for Store submission
        sign = true




        # Your signing certificate (see section 3)
        # certificate = "..."

        # If publishing to Microsoft Store, add these:
        store {
            # Get these from Partner Center's "Product Identity" page
            identity-name = "RealtechSolutions.Papertrack"
            publisher = "CN=88C72730-CB4E-4AD6-B436-23F0DFC38510"
            publisher-display-name = "Realtech Solutions"
            store-id = "9P902GPC04FT"
        }
    }
}
conveyor.compatibility-level = 22


